#pragma once

#include "Core/BasicTypes.hpp"
#include "Core/Serialization.hpp"
#include "Core/ObjectBase.hpp"
#include "Core/Singleton.hpp"
#include "Core/Assert/Assert.hpp"
#include "Core/Memory.hpp"
#include "Core/ClassManager.hpp"
#include "Core/Subsystem.hpp"
#include "Core/Proxy/ProxyObject.hpp"
#include "Core/Functor.hpp"
#include "Core/File/File.hpp"
#include "Core/Log/Log.hpp"
#include "Core/Time/TimeUtils.hpp"
#include "Core/Time/TimerManager.hpp"
#include "Core/Profiler/Profiler.hpp"